name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clojure deps cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-cljdeps-${{ hashFiles('project.clj') }}
        restore-keys: ${{ runner.os }}-cljdeps-

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 24

    - name: Install Clojure Tools
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        lein: 'latest'

    - name: Download deps
      run: lein all deps

    - name: Tools Versions
      run: |
        echo "java -version"
        java -version
        echo "lein --version"
        lein --version

    - name: Lint with eastwood
      run: lein eastwood

    - name: Lint with clj-kondo
      run: lein clj-kondo-lint

  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows ]
        java-version: [ '8', '11', '17', '21', '24' ]

    defaults:
      run:
        # Windows lein.ps1 script is problematic, force lein.bat by using cmd shell
        shell: ${{ matrix.os == 'windows' && 'cmd' || 'bash' }}

    name: test ${{matrix.os}} jdk${{matrix.java-version}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clojure deps cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-cljdeps-${{ hashFiles('project.clj') }}
        restore-keys: ${{ runner.os }}-cljdeps-

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Install Clojure Tools
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        lein: 'latest'

    - name: Download deps
      run: lein all deps

    - name: Tools Versions
      run: |
        echo "java -version"
        java -version
        echo "lein --version"
        lein --version

    - name: Run Tests
      run: lein all test :all
